version: "{branch} #{build}"

image:
  - Visual Studio 2017
  - Visual Studio 2019

platform:
  - Win32
  - x64

build:
  parallel: true

build_script:
  - cmake -A %PLATFORM%
  - cmake --build . --config Debug
  - cmake --build . --config Release
