name: ubuntu

on: [push, pull_request]

permissions: read-all

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - { name: "GCC 14",   cxx: "g++-14",      os: "ubuntu-24.04" }
        - { name: "Clang 18", cxx: "clang++-18",  os: "ubuntu-24.04" }

    name: "${{ matrix.compiler.name }}"
    runs-on: ${{ matrix.compiler.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Build Release
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }}
        cmake --build . -j 4 --config Release
        ctest --output-on-failure -C Release

    - name: Build Debug
      run: |
        rm -rf build
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }}
        cmake --build . -j 4 --config Debug
        ctest --output-on-failure -C Debug
